name: github action

on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Specify the Python version

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests
      - name: Run Tests
        run: |
          python -m unittest
      # Run publish once
      - name: Run once
        run: python main.py
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}




###################dispatch#################
#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - '*'
#run-name: ${{ github.actor }} is testing out GitHub Actions  🚀
#
#jobs:
#  trigger:
#    runs-on: ubuntu-latest
#    steps:
#      - name: trigger the automated test in another repo
#        uses: peter-evans/repository-dispatch@v3
#        with:
#          token: '${{ secrets.PAT_TOKEN }}'
#          repository: username/target repository name
#          event-type: Integration-with-Automation
#      - name: my-step
#        run: 'echo ${{ github.actor }} Hello !'
#########################################################################